# fly.toml app configuration file generated for frontend-fragrant-shadow-7972 on 2025-09-29T14:41:50+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frontend-fragrant-shadow-7972"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# --- ADD THIS SECTION ---
# This tells the app to expect a BACKEND_URL environment variable at runtime.
[env]
  BACKEND_URL = "http://placeholder.internal"