services:
  backend:
    image: bobs24/fashion-gallery-backend:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    image: bobs24/fashion-gallery-frontend:latest
    restart: always
    ports:
      - "80:80" 
    depends_on:
      - backend

networks:
  default:
    driver: bridge