name: Deploy to Fly.io

# This workflow runs automatically every time you push to the 'main' branch
on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend Service
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # Set secrets for the backend app before deploying.
          flyctl secrets set \
            GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
            METABASE_URL="${{ secrets.METABASE_URL }}" \
            METABASE_USERNAME="${{ secrets.METABASE_USERNAME }}" \
            METABASE_PASSWORD="${{ secrets.METABASE_PASSWORD }}" \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_KEY="${{ secrets.SUPABASE_KEY }}" \
            --app backend-rough-shape-1306
          
          # Now, deploy the application.
          flyctl deploy --config fly.toml --app backend-rough-shape-1306

      - name: Deploy Frontend Service
        working-directory: ./frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config fly.toml --app frontend-fragrant-shadow-7972